# Generated by Django 6.0 on 2026-01-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
